'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace EdfaliService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="NewEdfaliSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class NewEdfali
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private DoPTransOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OnlineConfTransOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApplication1.My.MySettings.Default.WindowsApplication1_EdfaliService_NewEdfali
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event DoPTransCompleted As DoPTransCompletedEventHandler
        
        '''<remarks/>
        Public Event OnlineConfTransCompleted As OnlineConfTransCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoPTrans", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DoPTrans(ByVal Mobile As String, ByVal Pin As String, ByVal Cmobile As String, ByVal Amount As Decimal, ByVal PW As String) As String
            Dim results() As Object = Me.Invoke("DoPTrans", New Object() {Mobile, Pin, Cmobile, Amount, PW})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DoPTransAsync(ByVal Mobile As String, ByVal Pin As String, ByVal Cmobile As String, ByVal Amount As Decimal, ByVal PW As String)
            Me.DoPTransAsync(Mobile, Pin, Cmobile, Amount, PW, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DoPTransAsync(ByVal Mobile As String, ByVal Pin As String, ByVal Cmobile As String, ByVal Amount As Decimal, ByVal PW As String, ByVal userState As Object)
            If (Me.DoPTransOperationCompleted Is Nothing) Then
                Me.DoPTransOperationCompleted = AddressOf Me.OnDoPTransOperationCompleted
            End If
            Me.InvokeAsync("DoPTrans", New Object() {Mobile, Pin, Cmobile, Amount, PW}, Me.DoPTransOperationCompleted, userState)
        End Sub
        
        Private Sub OnDoPTransOperationCompleted(ByVal arg As Object)
            If (Not (Me.DoPTransCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DoPTransCompleted(Me, New DoPTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnlineConfTrans", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OnlineConfTrans(ByVal Mobile As String, ByVal Pin As String, ByVal sessionID As String, ByVal PW As String) As String
            Dim results() As Object = Me.Invoke("OnlineConfTrans", New Object() {Mobile, Pin, sessionID, PW})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OnlineConfTransAsync(ByVal Mobile As String, ByVal Pin As String, ByVal sessionID As String, ByVal PW As String)
            Me.OnlineConfTransAsync(Mobile, Pin, sessionID, PW, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OnlineConfTransAsync(ByVal Mobile As String, ByVal Pin As String, ByVal sessionID As String, ByVal PW As String, ByVal userState As Object)
            If (Me.OnlineConfTransOperationCompleted Is Nothing) Then
                Me.OnlineConfTransOperationCompleted = AddressOf Me.OnOnlineConfTransOperationCompleted
            End If
            Me.InvokeAsync("OnlineConfTrans", New Object() {Mobile, Pin, sessionID, PW}, Me.OnlineConfTransOperationCompleted, userState)
        End Sub
        
        Private Sub OnOnlineConfTransOperationCompleted(ByVal arg As Object)
            If (Not (Me.OnlineConfTransCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OnlineConfTransCompleted(Me, New OnlineConfTransCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DoPTransCompletedEventHandler(ByVal sender As Object, ByVal e As DoPTransCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DoPTransCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub OnlineConfTransCompletedEventHandler(ByVal sender As Object, ByVal e As OnlineConfTransCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OnlineConfTransCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
